---
Brands:
    - American
    - Continental
    - Festival
    - Imperial
    - Luxor
    - Tower
    - Worldwide
    - Globex
    - Soylent
    - Initech
    - Umbrella
    - Hooli
    - Vehement
    - Massive Dynamic
    - Tyrell
    - Wayne
    - Spacely
    - Queen
    - Parker
    - Bonsai
    - General
    - Galaxy!
    - Iceberg
    - Mammoth
    - Associated
    - Eastern
    - Mulligan
    - Islander
    - Acute
    - Tiny Turtle
    - Beta
    - Theta
    - Foggy Bottom
    - Adventure
    - Cobalt
    - Burgundy
    - Thistle
    - Willow
    - Glacier
    - Royal
    - Olympic
    - Captain
    - Admiral
    - Commodore
    - Indigo
    - Mulberry
    - Glass
    - Scientific
    - Steely
    - Lighthouse
