---
LotTemplates:
  TW:
    BuildingType: Townhouse
    Facing: West
    Width: 1
    Height: 1
  TE:
    BuildingType: Townhouse
    Facing: West
    Width: 1
    Height: 1
  
BlockTemplates:
  Townhouses:  
    Lots:
      - Name: TW
        Position: {x: 0, y: 0}
      - Name: TW
        Position: {x: 0, y: 1}
      - Name: TW
        Position: {x: 0, y: 2}
      - Name: TW
        Position: {x: 0, y: 3}
      - Name: TW
        Position: {x: 0, y: 4}
      - Name: TW
        Position: {x: 0, y: 5}
      - Name: TW
        Position: {x: 0, y: 6}
      - Name: TW
        Position: {x: 0, y: 7}
      - Name: TW
        Position: {x: 0, y: 8}
      - Name: TW
        Position: {x: 0, y: 9}
      - Name: TW
        Position: {x: 0, y: 10}
      - Name: TW
        Position: {x: 0, y: 11}
      - Name: TW
        Position: {x: 0, y: 12}
      - Name: TW
        Position: {x: 0, y: 13}
      - Name: TE
        Position: {x: 1, y: 0}
      - Name: TE
        Position: {x: 1, y: 1}
      - Name: TE
        Position: {x: 1, y: 2}
      - Name: TE
        Position: {x: 1, y: 3}
      - Name: TE
        Position: {x: 1, y: 4}
      - Name: TE
        Position: {x: 1, y: 5}
      - Name: TE
        Position: {x: 1, y: 6}
      - Name: TE
        Position: {x: 1, y: 7}
      - Name: TE
        Position: {x: 1, y: 8}
      - Name: TE
        Position: {x: 1, y: 9}
      - Name: TE
        Position: {x: 1, y: 10}
      - Name: TE
        Position: {x: 1, y: 11}
      - Name: TE
        Position: {x: 1, y: 12}
      - Name: TE
        Position: {x: 1, y: 13}


Neighborhoods:
  - Width: 60
    Height: 60
    Roads:
    - Start: {x: 0, y: 0}
      End:   {x: 59, y: 0}
    - Start: {x: 0, y: 15}
      End:   {x: 59, y: 15}
    - Start: {x: 0, y: 30}
      End:   {x: 59, y: 30}
    - Start: {x: 0, y: 45}
      End:   {x: 59, y: 45}
    - Start: {x: 0, y: 0}
      End:   {x: 59, y: 0}
    - Start: {x: 0, y: 0}
      End:   {x: 0, y: 59}
    - Start: {x: 3, y: 0}
      End:   {x: 3, y: 59}
    - Start: {x: 6, y: 0}
      End:   {x: 6, y: 59}
    - Start: {x: 9, y: 0}
      End:   {x: 9, y: 59}
    - Start: {x: 12, y: 0}
      End:   {x: 12, y: 59}
    - Start: {x: 15, y: 0}
      End:   {x: 15, y: 59}
    - Start: {x: 18, y: 0}
      End:   {x: 18, y: 59}
    - Start: {x: 21, y: 0}
      End:   {x: 21, y: 59}
    - Start: {x: 24, y: 0}
      End:   {x: 24, y: 59}
    - Start: {x: 27, y: 0}
      End:   {x: 27, y: 59}
    - Start: {x: 33, y: 0}
      End:   {x: 33, y: 59}
    - Start: {x: 36, y: 0}
      End:   {x: 36, y: 59}
    - Start: {x: 39, y: 0}
      End:   {x: 39, y: 59}
    - Start: {x: 42, y: 0}
      End:   {x: 42, y: 59}
    - Start: {x: 45, y: 0}
      End:   {x: 45, y: 59}
    - Start: {x: 48, y: 0}
      End:   {x: 48, y: 59}
    - Start: {x: 51, y: 0}
      End:   {x: 51, y: 59}
    - Start: {x: 54, y: 0}
      End:   {x: 54, y: 59}
    - Start: {x: 57, y: 0}
      End:   {x: 57, y: 59}

    Blocks:
      - Name: Townhouses
        Position: {x: 1, y: 1}
      - Name: Townhouses
        Position: {x: 4, y: 1}
      - Name: Townhouses
        Position: {x: 7, y: 1}
      - Name: Townhouses
        Position: {x: 10, y: 1}
      - Name: Townhouses
        Position: {x: 13, y: 1}
      - Name: Townhouses
        Position: {x: 16, y: 1}
      - Name: Townhouses
        Position: {x: 19, y: 1}
      - Name: Townhouses
        Position: {x: 22, y: 1}
      - Name: Townhouses
        Position: {x: 25, y: 1}
      - Name: Townhouses
        Position: {x: 34, y: 1}
      - Name: Townhouses
        Position: {x: 37, y: 1}
      - Name: Townhouses
        Position: {x: 40, y: 1}
      - Name: Townhouses
        Position: {x: 43, y: 1}
      - Name: Townhouses
        Position: {x: 46, y: 1}
      - Name: Townhouses
        Position: {x: 49, y: 1}
      - Name: Townhouses
        Position: {x: 52, y: 1}
      - Name: Townhouses
        Position: {x: 55, y: 1}
      - Name: Townhouses
        Position: {x: 58, y: 1}
      - Name: Townhouses
        Position: {x: 1, y: 16}
      - Name: Townhouses
        Position: {x: 4, y: 16}
      - Name: Townhouses
        Position: {x: 7, y: 16}
      - Name: Townhouses
        Position: {x: 10, y: 16}
      - Name: Townhouses
        Position: {x: 13, y: 16}
      - Name: Townhouses
        Position: {x: 16, y: 16}
      - Name: Townhouses
        Position: {x: 19, y: 16}
      - Name: Townhouses
        Position: {x: 22, y: 16}
      - Name: Townhouses
        Position: {x: 25, y: 16}
      - Name: Townhouses
        Position: {x: 34, y: 16}
      - Name: Townhouses
        Position: {x: 37, y: 16}
      - Name: Townhouses
        Position: {x: 40, y: 16}
      - Name: Townhouses
        Position: {x: 43, y: 16}
      - Name: Townhouses
        Position: {x: 46, y: 16}
      - Name: Townhouses
        Position: {x: 49, y: 16}
      - Name: Townhouses
        Position: {x: 52, y: 16}
      - Name: Townhouses
        Position: {x: 55, y: 16}
      - Name: Townhouses
        Position: {x: 58, y: 16}
      - Name: Townhouses
        Position: {x: 1, y: 31}
      - Name: Townhouses
        Position: {x: 4, y: 31}
      - Name: Townhouses
        Position: {x: 7, y: 31}
      - Name: Townhouses
        Position: {x: 10, y: 31}
      - Name: Townhouses
        Position: {x: 13, y: 31}
      - Name: Townhouses
        Position: {x: 16, y: 31}
      - Name: Townhouses
        Position: {x: 19, y: 31}
      - Name: Townhouses
        Position: {x: 22, y: 31}
      - Name: Townhouses
        Position: {x: 25, y: 31}
      - Name: Townhouses
        Position: {x: 34, y: 31}
      - Name: Townhouses
        Position: {x: 37, y: 31}
      - Name: Townhouses
        Position: {x: 40, y: 31}
      - Name: Townhouses
        Position: {x: 43, y: 31}
      - Name: Townhouses
        Position: {x: 46, y: 31}
      - Name: Townhouses
        Position: {x: 49, y: 31}
      - Name: Townhouses
        Position: {x: 52, y: 31}
      - Name: Townhouses
        Position: {x: 55, y: 31}
      - Name: Townhouses
        Position: {x: 58, y: 31}
      - Name: Townhouses
        Position: {x: 1, y: 46}
      - Name: Townhouses
        Position: {x: 4, y: 46}
      - Name: Townhouses
        Position: {x: 7, y: 46}
      - Name: Townhouses
        Position: {x: 10, y: 46}
      - Name: Townhouses
        Position: {x: 13, y: 46}
      - Name: Townhouses
        Position: {x: 16, y: 46}
      - Name: Townhouses
        Position: {x: 19, y: 46}
      - Name: Townhouses
        Position: {x: 22, y: 46}
      - Name: Townhouses
        Position: {x: 25, y: 46}
      - Name: Townhouses
        Position: {x: 34, y: 46}
      - Name: Townhouses
        Position: {x: 37, y: 46}
      - Name: Townhouses
        Position: {x: 40, y: 46}
      - Name: Townhouses
        Position: {x: 43, y: 46}
      - Name: Townhouses
        Position: {x: 46, y: 46}
      - Name: Townhouses
        Position: {x: 49, y: 46}
      - Name: Townhouses
        Position: {x: 52, y: 46}
      - Name: Townhouses
        Position: {x: 55, y: 46}
      - Name: Townhouses
        Position: {x: 58, y: 46}