---
LotTemplates:
  TW:
    BuildingType: Townhouse
    Facing: West
    Width: 1
    Height: 1
  TE:
    BuildingType: Townhouse
    Facing: East
    Width: 1
    Height: 1
  Apartment:
    BuildingType: Apartment
    Width: 5
    Height: 5
    Facing: East
  Headquarters:
    BuildingType: Headquarters
    Width: 5
    Height: 5
    Facing: East
  Office:
    BuildingType: Office
    Width: 5
    Height: 5
    Facing: East
  RanchE:
    BuildingType: Ranch
    Width: 3
    Height: 3
    Facing: East
  RanchW:
    BuildingType: Ranch
    Width: 3
    Height: 3
    Facing: West
  Retail:
    BuildingType: Retail
    Width: 5
    Height: 5
    Facing: East
  SmallHouseN:
    BuildingType: SmallHouse
    Width: 3
    Height: 2
    Facing: North
  SmallHouseE:
    BuildingType: SmallHouse
    Width: 2
    Height: 3
    Facing: East
  SmallHouseW:
    BuildingType: SmallHouse
    Width: 2
    Height: 3
    Facing: West
  SmallRetailE:
    BuildingType: SmallRetail
    Width: 3
    Height: 3
    Facing: East
  SmallRetailW:
    BuildingType: SmallRetail
    Width: 3
    Height: 3
    Facing: West
  SmallRetail2E:
    BuildingType: SmallRetail2
    Width: 2
    Height: 3
    Facing: East
  SmallRetail2W:
    BuildingType: SmallRetail2
    Width: 2
    Height: 3
    Facing: West
  StripMallE:
    BuildingType: StripMall
    Width: 3
    Height: 3
    Facing: East
  StripMallW:
    BuildingType: StripMall
    Width: 3
    Height: 3
    Facing: West
  SuburbanHouseE: 
    BuildingType: SuburbanHouse
    Width: 2
    Height: 3
    Facing: East
  SuburbanHouseW:
    BuildingType: SuburbanHouse
    Width: 2
    Height: 3
    Facing: West
  Warehouse:
    BuildingType: Warehouse
    Width: 5
    Height: 9
    Facing: East
  
BlockTemplates:
  Ranches:
    Lots:
      - Name: RanchW
        Position: {x: 0, y: 0}
      - Name: RanchW
        Position: {x: 0, y: 3}
      - Name: RanchW
        Position: {x: 0, y: 6}
      - Name: RanchW
        Position: {x: 0, y: 9}
      - Name: RanchW
        Position: {x: 0, y: 12}
      - Name: RanchW
        Position: {x: 0, y: 15}
      - Name: RanchW
        Position: {x: 0, y: 18}
      - Name: RanchW
        Position: {x: 0, y: 21}
      - Name: RanchW
        Position: {x: 0, y: 24}
      - Name: SmallHouseN
        Position: {x: 0, y: 26}
      - Name: RanchE
        Position: {x: 3, y: 0}
      - Name: RanchE
        Position: {x: 3, y: 3}
      - Name: RanchE
        Position: {x: 3, y: 6}
      - Name: RanchE
        Position: {x: 3, y: 9}
      - Name: RanchE
        Position: {x: 3, y: 12}
      - Name: RanchE
        Position: {x: 3, y: 15}
      - Name: RanchE
        Position: {x: 3, y: 18}
      - Name: RanchE
        Position: {x: 3, y: 21}
      - Name: RanchE
        Position: {x: 3, y: 24}
      - Name: SmallHouseN
        Position: {x: 3, y: 26}

  Warehouses:
    Lots: 
      - Name: Warehouse
        Position: {x: 0, y: 0}
      - Name: Warehouse
        Position: {x: 0, y: 10}

  WarehouseAndRetail:
    Lots:
      - Name: Warehouse
        Position: {x: 0, y: 0}
      - Name: Retail
        Position: {x: 0, y: 9}

  Apartments:
    Lots:
      - Name: Apartment
        Position: {x: 0, y: 0}
      - Name: Apartment
        Position: {x: 0, y: 6}
      - Name: Apartment
        Position: {x: 0, y: 12}

  Offices:
    Lots:
      - Name: Office
        Position: {x: 0, y: 0}
      - Name: Office
        Position: {x: 0, y: 6}
      - Name: Office
        Position: {x: 0, y: 12}

  Retail:
    Lots: 
      - Name: Retail
        Position: {x: 0, y: 0}
      - Name: Retail
        Position: {x: 0, y: 5}
      - Name: Retail
        Position: {x: 0, y: 10}
      - Name: SmallRetailW
        Position: {x: 0, y: 16}
  
  StripMall:
    Lots:
      - Name: StripMallW
        Position: {x: 0, y: 0}
      - Name: StripMallW
        Position: {x: 0, y: 3}
      - Name: StripMallW
        Position: {x: 0, y: 6}
      - Name: StripMallW
        Position: {x: 0, y: 9}
      - Name: StripMallW
        Position: {x: 0, y: 12}
      - Name: StripMallW
        Position: {x: 0, y: 15}
      - Name: StripMallW
        Position: {x: 0, y: 18}
      - Name: StripMallW
        Position: {x: 0, y: 21}
      - Name: StripMallW
        Position: {x: 0, y: 24}
  
  Suburbs:
    Lots:
      - Name: SmallHouseW
        Position: {x: 0, y: 0}
      - Name: SuburbanHouseW
        Position: {x: 0, y: 3}
      - Name: SmallHouseW
        Position: {x: 0, y: 6}
      - Name: SuburbanHouseW
        Position: {x: 0, y: 9}
      - Name: SmallHouseW
        Position: {x: 0, y: 12}
      - Name: SuburbanHouseW
        Position: {x: 0, y: 15} 
      - Name: SmallHouseE
        Position: {x: 3, y: 0}
      - Name: SuburbanHouseE
        Position: {x: 3, y: 3}
      - Name: SmallHouseE
        Position: {x: 3, y: 6}
      - Name: SuburbanHouseE
        Position: {x: 3, y: 9}
      - Name: SmallHouseE
        Position: {x: 3, y: 12}
      - Name: SuburbanHouseE
        Position: {x: 3 , y: 15} 


  Townhouses:  
    Lots:
      - Name: TW
        Position: {x: 0, y: 0}
      - Name: TW
        Position: {x: 0, y: 1}
      - Name: TW
        Position: {x: 0, y: 2}
      - Name: TW
        Position: {x: 0, y: 3}
      - Name: TW
        Position: {x: 0, y: 4}
      - Name: TW
        Position: {x: 0, y: 5}
      - Name: TW
        Position: {x: 0, y: 6}
      - Name: TW
        Position: {x: 0, y: 7}
      - Name: TW
        Position: {x: 0, y: 8}
      - Name: TW
        Position: {x: 0, y: 9}
      - Name: TW
        Position: {x: 0, y: 10}
      - Name: TW
        Position: {x: 0, y: 11}
      - Name: TW
        Position: {x: 0, y: 12}
      - Name: TW
        Position: {x: 0, y: 13}
      - Name: TE
        Position: {x: 1, y: 0}
      - Name: TE
        Position: {x: 1, y: 1}
      - Name: TE
        Position: {x: 1, y: 2}
      - Name: TE
        Position: {x: 1, y: 3}
      - Name: TE
        Position: {x: 1, y: 4}
      - Name: TE
        Position: {x: 1, y: 5}
      - Name: TE
        Position: {x: 1, y: 6}
      - Name: TE
        Position: {x: 1, y: 7}
      - Name: TE
        Position: {x: 1, y: 8}
      - Name: TE
        Position: {x: 1, y: 9}
      - Name: TE
        Position: {x: 1, y: 10}
      - Name: TE
        Position: {x: 1, y: 11}
      - Name: TE
        Position: {x: 1, y: 12}
      - Name: TE
        Position: {x: 1, y: 13}


Neighborhoods:
# Suburban neighborhood -- 5x19 internal block size
  - Width: 60
    Height: 60
    Roads:
    - Start: {x: 0, y: 0}
      End:   {x: 59, y: 0}
    - Start: {x: 0, y: 20}
      End:   {x: 59, y: 20}
    - Start: {x: 0, y: 40}
      End:   {x: 59, y: 40}
    - Start: {x: 0, y: 0}
      End:   {x: 0, y: 59}
    - Start: {x: 6, y: 0}
      End:   {x: 6, y: 59}
    - Start: {x: 12, y: 0}
      End:   {x: 12, y: 59}
    - Start: {x: 18, y: 0}
      End:   {x: 18, y: 59}
    - Start: {x: 24, y: 0}
      End:   {x: 24, y: 59}
    - Start: {x: 30, y: 0}
      End:   {x: 30, y: 59}
    - Start: {x: 36, y: 0}
      End:   {x: 36, y: 59}
    - Start: {x: 42, y: 0}
      End:   {x: 42, y: 59}
    - Start: {x: 48, y: 0}
      End:   {x: 48, y: 59}
    - Start: {x: 54, y: 0}
      End:   {x: 54, y: 59}
    Blocks:
      - Name: Suburbs
        Position: {x: 1, y: 1}
      - Name: Suburbs
        Position: {x: 7, y: 1}
      - Name: Suburbs
        Position: {x: 13, y: 1}
      - Name: Suburbs
        Position: {x: 19, y: 1}
      - Name: Suburbs
        Position: {x: 25, y: 1}
      - Name: Suburbs
        Position: {x: 31, y: 1}
      - Name: Suburbs
        Position: {x: 37, y: 1}
      - Name: Suburbs
        Position: {x: 43, y: 1}
      - Name: Suburbs
        Position: {x: 49, y: 1}
      - Name: Suburbs
        Position: {x: 55, y: 1}
      - Name: Apartments
        Position: {x: 1, y: 21}
      - Name: Offices
        Position: {x: 7, y: 21}
      - Name: Apartments
        Position: {x: 13, y: 21}
      - Name: Apartments
        Position: {x: 19, y: 21}
      - Name: Retail
        Position: {x: 25, y: 21}
      - Name: Warehouses
        Position: {x: 31, y: 21}
      - Name: Apartments
        Position: {x: 37, y: 21}
      - Name: Offices
        Position: {x: 43, y: 21}
      - Name: Apartments
        Position: {x: 49, y: 21}
      - Name: Apartments
        Position: {x: 55, y: 21}
      - Name: Suburbs
        Position: {x: 1, y: 41}
      - Name: Suburbs
        Position: {x: 7, y: 41}
      - Name: Suburbs
        Position: {x: 13, y: 41}
      - Name: Suburbs
        Position: {x: 19, y: 41}
      - Name: Suburbs
        Position: {x: 25, y: 41}
      - Name: Suburbs
        Position: {x: 31, y: 41}
      - Name: Suburbs
        Position: {x: 37, y: 41}
      - Name: Suburbs
        Position: {x: 43, y: 41}
      - Name: Suburbs
        Position: {x: 49, y: 41}
      - Name: Suburbs
        Position: {x: 55, y: 41}


# Suburban neighborhood -- 6x29 internal block size
  - Width: 60
    Height: 60
    Roads:
      - Start: {x: 0, y: 0}
        End:   {x: 59, y: 0}
      - Start: {x: 0, y: 30}
        End:   {x: 59, y: 30}
      - Start: {x: 0, y: 0}
        End:   {x: 0, y: 59}
      - Start: {x: 7, y: 0}
        End:   {x: 7, y: 59}
      - Start: {x: 14, y: 0}
        End:   {x: 14, y: 59}
      - Start: {x: 21, y: 0}
        End:   {x: 21, y: 59}
      - Start: {x: 28, y: 0}
        End:   {x: 28, y: 59}
      - Start: {x: 32, y: 0}
        End:   {x: 32, y: 59}
      - Start: {x: 39, y: 0}
        End:   {x: 39, y: 59}
      - Start: {x: 46, y: 0}
        End:   {x: 46, y: 59}
      - Start: {x: 53, y: 0}
        End:   {x: 53, y: 59}
    Blocks:
      - Name: Ranches
        Position: {x: 1, y: 1}
      - Name: Ranches
        Position: {x: 8, y: 1}
      - Name: Ranches
        Position: {x: 15, y: 1}
      - Name: Ranches
        Position: {x: 22, y: 1}
      - Name: StripMall
        Position: {x: 29, y: 1}
      - Name: Ranches
        Position: {x: 33, y: 1}
      - Name: Ranches
        Position: {x: 40, y: 1}
      - Name: Ranches
        Position: {x: 47, y: 1}
      - Name: Ranches
        Position: {x: 54, y: 1}
      - Name: Ranches
        Position: {x: 1, y: 31}
      - Name: Ranches
        Position: {x: 8, y: 31}
      - Name: Ranches
        Position: {x: 15, y: 31}
      - Name: Ranches
        Position: {x: 22, y: 31}
      - Name: StripMall
        Position: {x: 29, y: 31}
      - Name: Ranches
        Position: {x: 33, y: 31}
      - Name: Ranches
        Position: {x: 40, y: 31}
      - Name: Ranches
        Position: {x: 47, y: 31}
      - Name: Ranches
        Position: {x: 54, y: 31}


# Townhouse neighborhood -- 2x14 internal block size
  - Width: 60
    Height: 60
    Roads:
      - Start: {x: 0, y: 0}
        End:   {x: 59, y: 0}
      - Start: {x: 0, y: 15}
        End:   {x: 59, y: 15}
      - Start: {x: 0, y: 30}
        End:   {x: 59, y: 30}
      - Start: {x: 0, y: 45}
        End:   {x: 59, y: 45}
      - Start: {x: 0, y: 0}
        End:   {x: 59, y: 0}
      - Start: {x: 0, y: 0}
        End:   {x: 0, y: 59}
      - Start: {x: 3, y: 0}
        End:   {x: 3, y: 59}
      - Start: {x: 6, y: 0}
        End:   {x: 6, y: 59}
      - Start: {x: 9, y: 0}
        End:   {x: 9, y: 59}
      - Start: {x: 12, y: 0}
        End:   {x: 12, y: 59}
      - Start: {x: 15, y: 0}
        End:   {x: 15, y: 59}
      - Start: {x: 18, y: 0}
        End:   {x: 18, y: 59}
      - Start: {x: 21, y: 0}
        End:   {x: 21, y: 59}
      - Start: {x: 24, y: 0}
        End:   {x: 24, y: 59}
      - Start: {x: 27, y: 0}
        End:   {x: 27, y: 59}
      - Start: {x: 33, y: 0}
        End:   {x: 33, y: 59}
      - Start: {x: 36, y: 0}
        End:   {x: 36, y: 59}
      - Start: {x: 39, y: 0}
        End:   {x: 39, y: 59}
      - Start: {x: 42, y: 0}
        End:   {x: 42, y: 59}
      - Start: {x: 45, y: 0}
        End:   {x: 45, y: 59}
      - Start: {x: 48, y: 0}
        End:   {x: 48, y: 59}
      - Start: {x: 51, y: 0}
        End:   {x: 51, y: 59}
      - Start: {x: 54, y: 0}
        End:   {x: 54, y: 59}
      - Start: {x: 57, y: 0}
        End:   {x: 57, y: 59}

    Blocks:
      - Name: Townhouses
        Position: {x: 1, y: 1}
      - Name: Townhouses
        Position: {x: 4, y: 1}
      - Name: Townhouses
        Position: {x: 7, y: 1}
      - Name: Townhouses
        Position: {x: 10, y: 1}
      - Name: Townhouses
        Position: {x: 13, y: 1}
      - Name: Townhouses
        Position: {x: 16, y: 1}
      - Name: Townhouses
        Position: {x: 19, y: 1}
      - Name: Townhouses
        Position: {x: 22, y: 1}
      - Name: Townhouses
        Position: {x: 25, y: 1}
      - Name: Townhouses
        Position: {x: 34, y: 1}
      - Name: Townhouses
        Position: {x: 37, y: 1}
      - Name: Townhouses
        Position: {x: 40, y: 1}
      - Name: Townhouses
        Position: {x: 43, y: 1}
      - Name: Townhouses
        Position: {x: 46, y: 1}
      - Name: Townhouses
        Position: {x: 49, y: 1}
      - Name: Townhouses
        Position: {x: 52, y: 1}
      - Name: Townhouses
        Position: {x: 55, y: 1}
      - Name: Townhouses
        Position: {x: 58, y: 1}
      - Name: Townhouses
        Position: {x: 1, y: 16}
      - Name: Townhouses
        Position: {x: 4, y: 16}
      - Name: Townhouses
        Position: {x: 7, y: 16}
      - Name: Townhouses
        Position: {x: 10, y: 16}
      - Name: Townhouses
        Position: {x: 13, y: 16}
      - Name: Townhouses
        Position: {x: 16, y: 16}
      - Name: Townhouses
        Position: {x: 19, y: 16}
      - Name: Townhouses
        Position: {x: 22, y: 16}
      - Name: Townhouses
        Position: {x: 25, y: 16}
      - Name: Townhouses
        Position: {x: 34, y: 16}
      - Name: Townhouses
        Position: {x: 37, y: 16}
      - Name: Townhouses
        Position: {x: 40, y: 16}
      - Name: Townhouses
        Position: {x: 43, y: 16}
      - Name: Townhouses
        Position: {x: 46, y: 16}
      - Name: Townhouses
        Position: {x: 49, y: 16}
      - Name: Townhouses
        Position: {x: 52, y: 16}
      - Name: Townhouses
        Position: {x: 55, y: 16}
      - Name: Townhouses
        Position: {x: 58, y: 16}
      - Name: Townhouses
        Position: {x: 1, y: 31}
      - Name: Townhouses
        Position: {x: 4, y: 31}
      - Name: Townhouses
        Position: {x: 7, y: 31}
      - Name: Townhouses
        Position: {x: 10, y: 31}
      - Name: Townhouses
        Position: {x: 13, y: 31}
      - Name: Townhouses
        Position: {x: 16, y: 31}
      - Name: Townhouses
        Position: {x: 19, y: 31}
      - Name: Townhouses
        Position: {x: 22, y: 31}
      - Name: Townhouses
        Position: {x: 25, y: 31}
      - Name: Townhouses
        Position: {x: 34, y: 31}
      - Name: Townhouses
        Position: {x: 37, y: 31}
      - Name: Townhouses
        Position: {x: 40, y: 31}
      - Name: Townhouses
        Position: {x: 43, y: 31}
      - Name: Townhouses
        Position: {x: 46, y: 31}
      - Name: Townhouses
        Position: {x: 49, y: 31}
      - Name: Townhouses
        Position: {x: 52, y: 31}
      - Name: Townhouses
        Position: {x: 55, y: 31}
      - Name: Townhouses
        Position: {x: 58, y: 31}
      - Name: Townhouses
        Position: {x: 1, y: 46}
      - Name: Townhouses
        Position: {x: 4, y: 46}
      - Name: Townhouses
        Position: {x: 7, y: 46}
      - Name: Townhouses
        Position: {x: 10, y: 46}
      - Name: Townhouses
        Position: {x: 13, y: 46}
      - Name: Townhouses
        Position: {x: 16, y: 46}
      - Name: Townhouses
        Position: {x: 19, y: 46}
      - Name: Townhouses
        Position: {x: 22, y: 46}
      - Name: Townhouses
        Position: {x: 25, y: 46}
      - Name: Townhouses
        Position: {x: 34, y: 46}
      - Name: Townhouses
        Position: {x: 37, y: 46}
      - Name: Townhouses
        Position: {x: 40, y: 46}
      - Name: Townhouses
        Position: {x: 43, y: 46}
      - Name: Townhouses
        Position: {x: 46, y: 46}
      - Name: Townhouses
        Position: {x: 49, y: 46}
      - Name: Townhouses
        Position: {x: 52, y: 46}
      - Name: Townhouses
        Position: {x: 55, y: 46}
      - Name: Townhouses
        Position: {x: 58, y: 46}
      - Name: WarehouseAndRetail
        Position: {x: 28, y: 1}
      - Name: WarehouseAndRetail
        Position: {x: 28, y: 16}
      - Name: WarehouseAndRetail
        Position: {x: 28, y: 31}
      - Name: WarehouseAndRetail
        Position: {x: 28, y: 46}

